version: '3.8'

services:
  postgres:
    image: postgres:12.22-alpine3.21
    container_name: db-postgres-new
    environment:
      POSTGRES_PASSWORD: 567234
      POSTGRES_USER: postgres
      POSTGRES_DB: db-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    driver: local
