"""Fix product, add info

Revision ID: ec361aa48603
Revises: 3e19e8f59091
Create Date: 2025-01-12 09:59:11.003575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec361aa48603'
down_revision: Union[str, None] = '3e19e8f59091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('info', sa.JSON(), nullable=True))
    op.drop_column('products', 'size')
    op.drop_column('products', 'is_private')
    op.drop_column('products', 'condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'info')
    op.drop_column('products', 'type')
    # ### end Alembic commands ###
